name: Deploy Build AMI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: zip files
        run: |
          zip -r webservice.zip ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var=aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}
           -var=aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} -var-file=./ami_vars.json"
          target: ./ami.json
        env:
          PACKER_LOG: 1
